name: Build

on: push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Install swift
      uses: YOCKOW/Action-setup-swift@v1
      with:
        swift-version: '5.5.1'
    - shell: bash
      env:
        MAILTRAPUSER: ${{ secrets.MAILTRAPUSER }}
      run: |
        sed -i -e 's/#MAILTRAPUSER#/'"$MAILTRAPUSER"'/g' Tests/AppTests/EmailsController/SendActionTests.swift
    - shell: bash
      env:
        MAILTRAPPASS: ${{ secrets.MAILTRAPPASS }}
      run: |
        sed -i -e 's/#MAILTRAPPASS#/'"$MAILTRAPPASS"'/g' Tests/AppTests/EmailsController/SendActionTests.swift
    - name: Install SQLite libs
      run: sudo apt-get install libsqlite3-dev
    - name: Build
      run: swift build
    - name: Tests
      run: swift test