name: Build

on: push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - uses: YOCKOW/Action-setup-swift@master
      with:
        swift-version: '5.3'
    - shell: bash
      env:
        MAILTRAPUSER: ${{ secrets.MAILTRAPUSER }}
      run: |
        sed -i -e 's/#MAILTRAPUSER#/'"$MAILTRAPUSER"'/g' Tests/AppTests/EmailsController/SendActionTests.swift
    - shell: bash
      env:
        MAILTRAPPASS: ${{ secrets.MAILTRAPPASS }}
      run: |
        sed -i -e 's/#MAILTRAPPASS#/'"$MAILTRAPPASS"'/g' Tests/AppTests/EmailsController/SendActionTests.swift
    - name: Install SQLite libs
      run: sudo apt-get install libsqlite3-dev
    - name: Build
      run: swift build --enable-test-discovery
    - name: Tests
      run: swift test --enable-test-discovery